# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_files_api import AdminFilesApi


class TestAdminFilesApi(unittest.TestCase):
    """AdminFilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminFilesApi()

    def tearDown(self) -> None:
        pass

    def test_get_admin_files_projectshortcode_filename(self) -> None:
        """Test case for get_admin_files_projectshortcode_filename

        """
        pass


if __name__ == '__main__':
    unittest.main()
