# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_permissions_api import AdminPermissionsApi


class TestAdminPermissionsApi(unittest.TestCase):
    """AdminPermissionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminPermissionsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_admin_permissions_permissioniri(self) -> None:
        """Test case for delete_admin_permissions_permissioniri

        """
        pass

    def test_get_admin_permissions_ap_projectiri(self) -> None:
        """Test case for get_admin_permissions_ap_projectiri

        """
        pass

    def test_get_admin_permissions_ap_projectiri_groupiri(self) -> None:
        """Test case for get_admin_permissions_ap_projectiri_groupiri

        """
        pass

    def test_get_admin_permissions_doap_projectiri(self) -> None:
        """Test case for get_admin_permissions_doap_projectiri

        """
        pass

    def test_get_admin_permissions_projectiri(self) -> None:
        """Test case for get_admin_permissions_projectiri

        """
        pass

    def test_post_admin_permissions_ap(self) -> None:
        """Test case for post_admin_permissions_ap

        """
        pass

    def test_post_admin_permissions_doap(self) -> None:
        """Test case for post_admin_permissions_doap

        """
        pass

    def test_put_admin_permissions_doap_permissioniri(self) -> None:
        """Test case for put_admin_permissions_doap_permissioniri

        """
        pass

    def test_put_admin_permissions_permissioniri_group(self) -> None:
        """Test case for put_admin_permissions_permissioniri_group

        """
        pass

    def test_put_admin_permissions_permissioniri_haspermissions(self) -> None:
        """Test case for put_admin_permissions_permissioniri_haspermissions

        """
        pass

    def test_put_admin_permissions_permissioniri_property(self) -> None:
        """Test case for put_admin_permissions_permissioniri_property

        """
        pass

    def test_put_admin_permissions_permissioniri_resourceclass(self) -> None:
        """Test case for put_admin_permissions_permissioniri_resourceclass

        """
        pass


if __name__ == '__main__':
    unittest.main()
