# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.string_literal_sequence_v2 import StringLiteralSequenceV2

class TestStringLiteralSequenceV2(unittest.TestCase):
    """StringLiteralSequenceV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StringLiteralSequenceV2:
        """Test StringLiteralSequenceV2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StringLiteralSequenceV2`
        """
        model = StringLiteralSequenceV2()
        if include_optional:
            return StringLiteralSequenceV2(
                string_literals = [
                    openapi_client.models.string_literal_v2.StringLiteralV2(
                        value = '', 
                        language = '', )
                    ]
            )
        else:
            return StringLiteralSequenceV2(
        )
        """

    def testStringLiteralSequenceV2(self):
        """Test StringLiteralSequenceV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
