# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_create_request import UserCreateRequest

class TestUserCreateRequest(unittest.TestCase):
    """UserCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserCreateRequest:
        """Test UserCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserCreateRequest`
        """
        model = UserCreateRequest()
        if include_optional:
            return UserCreateRequest(
                id = openapi_client.models.user_iri.UserIri(
                    value = '', ),
                username = openapi_client.models.username.Username(
                    value = '', ),
                email = openapi_client.models.email.Email(
                    value = '', ),
                given_name = openapi_client.models.given_name.GivenName(
                    value = '', ),
                family_name = openapi_client.models.family_name.FamilyName(
                    value = '', ),
                password = openapi_client.models.password.Password(
                    value = '', ),
                status = openapi_client.models.user_status.UserStatus(
                    value = True, ),
                lang = openapi_client.models.language_code.LanguageCode(
                    value = '', ),
                system_admin = openapi_client.models.system_admin.SystemAdmin(
                    value = True, )
            )
        else:
            return UserCreateRequest(
                username = openapi_client.models.username.Username(
                    value = '', ),
                email = openapi_client.models.email.Email(
                    value = '', ),
                given_name = openapi_client.models.given_name.GivenName(
                    value = '', ),
                family_name = openapi_client.models.family_name.FamilyName(
                    value = '', ),
                password = openapi_client.models.password.Password(
                    value = '', ),
                status = openapi_client.models.user_status.UserStatus(
                    value = True, ),
                lang = openapi_client.models.language_code.LanguageCode(
                    value = '', ),
                system_admin = openapi_client.models.system_admin.SystemAdmin(
                    value = True, ),
        )
        """

    def testUserCreateRequest(self):
        """Test UserCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
