# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_store_api import AdminStoreApi


class TestAdminStoreApi(unittest.TestCase):
    """AdminStoreApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminStoreApi()

    def tearDown(self) -> None:
        pass

    def test_get_admin_store_resettriplestorecontent(self) -> None:
        """Test case for get_admin_store_resettriplestorecontent

        """
        pass


if __name__ == '__main__':
    unittest.main()
