# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.v2_search_api import V2SearchApi


class TestV2SearchApi(unittest.TestCase):
    """V2SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = V2SearchApi()

    def tearDown(self) -> None:
        pass

    def test_get_v2_search_count_searchterm(self) -> None:
        """Test case for get_v2_search_count_searchterm

        """
        pass

    def test_get_v2_search_searchterm(self) -> None:
        """Test case for get_v2_search_searchterm

        """
        pass

    def test_get_v2_searchbylabel_count_searchterm(self) -> None:
        """Test case for get_v2_searchbylabel_count_searchterm

        """
        pass

    def test_get_v2_searchbylabel_searchterm(self) -> None:
        """Test case for get_v2_searchbylabel_searchterm

        """
        pass

    def test_get_v2_searchextended_count_p1(self) -> None:
        """Test case for get_v2_searchextended_count_p1

        """
        pass

    def test_get_v2_searchextended_p1(self) -> None:
        """Test case for get_v2_searchextended_p1

        """
        pass

    def test_get_v2_searchincominglinks_resourceiri(self) -> None:
        """Test case for get_v2_searchincominglinks_resourceiri

        """
        pass

    def test_get_v2_searchincomingregions_resourceiri(self) -> None:
        """Test case for get_v2_searchincomingregions_resourceiri

        """
        pass

    def test_post_v2_searchextended(self) -> None:
        """Test case for post_v2_searchextended

        """
        pass

    def test_post_v2_searchextended_count(self) -> None:
        """Test case for post_v2_searchextended_count

        """
        pass


if __name__ == '__main__':
    unittest.main()
