# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.project_keywords_get_response import ProjectKeywordsGetResponse

class TestProjectKeywordsGetResponse(unittest.TestCase):
    """ProjectKeywordsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectKeywordsGetResponse:
        """Test ProjectKeywordsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectKeywordsGetResponse`
        """
        model = ProjectKeywordsGetResponse()
        if include_optional:
            return ProjectKeywordsGetResponse(
                keywords = [
                    ''
                    ]
            )
        else:
            return ProjectKeywordsGetResponse(
        )
        """

    def testProjectKeywordsGetResponse(self):
        """Test ProjectKeywordsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
