# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_projects_api import AdminProjectsApi


class TestAdminProjectsApi(unittest.TestCase):
    """AdminProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_admin_projects_iri_projectiri(self) -> None:
        """Test case for delete_admin_projects_iri_projectiri

        """
        pass

    def test_delete_admin_projects_shortcode_projectshortcode_erase(self) -> None:
        """Test case for delete_admin_projects_shortcode_projectshortcode_erase

        """
        pass

    def test_get_admin_projects(self) -> None:
        """Test case for get_admin_projects

        """
        pass

    def test_get_admin_projects_export(self) -> None:
        """Test case for get_admin_projects_export

        """
        pass

    def test_get_admin_projects_iri_projectiri(self) -> None:
        """Test case for get_admin_projects_iri_projectiri

        """
        pass

    def test_get_admin_projects_iri_projectiri_admin_members(self) -> None:
        """Test case for get_admin_projects_iri_projectiri_admin_members

        """
        pass

    def test_get_admin_projects_iri_projectiri_alldata(self) -> None:
        """Test case for get_admin_projects_iri_projectiri_alldata

        """
        pass

    def test_get_admin_projects_iri_projectiri_keywords(self) -> None:
        """Test case for get_admin_projects_iri_projectiri_keywords

        """
        pass

    def test_get_admin_projects_iri_projectiri_members(self) -> None:
        """Test case for get_admin_projects_iri_projectiri_members

        """
        pass

    def test_get_admin_projects_iri_projectiri_restrictedviewsettings(self) -> None:
        """Test case for get_admin_projects_iri_projectiri_restrictedviewsettings

        """
        pass

    def test_get_admin_projects_keywords(self) -> None:
        """Test case for get_admin_projects_keywords

        """
        pass

    def test_get_admin_projects_shortcode_projectshortcode(self) -> None:
        """Test case for get_admin_projects_shortcode_projectshortcode

        """
        pass

    def test_get_admin_projects_shortcode_projectshortcode_admin_members(self) -> None:
        """Test case for get_admin_projects_shortcode_projectshortcode_admin_members

        """
        pass

    def test_get_admin_projects_shortcode_projectshortcode_members(self) -> None:
        """Test case for get_admin_projects_shortcode_projectshortcode_members

        """
        pass

    def test_get_admin_projects_shortcode_projectshortcode_restrictedviewsettings(self) -> None:
        """Test case for get_admin_projects_shortcode_projectshortcode_restrictedviewsettings

        """
        pass

    def test_get_admin_projects_shortname_projectshortname(self) -> None:
        """Test case for get_admin_projects_shortname_projectshortname

        """
        pass

    def test_get_admin_projects_shortname_projectshortname_admin_members(self) -> None:
        """Test case for get_admin_projects_shortname_projectshortname_admin_members

        """
        pass

    def test_get_admin_projects_shortname_projectshortname_members(self) -> None:
        """Test case for get_admin_projects_shortname_projectshortname_members

        """
        pass

    def test_get_admin_projects_shortname_projectshortname_restrictedviewsettings(self) -> None:
        """Test case for get_admin_projects_shortname_projectshortname_restrictedviewsettings

        """
        pass

    def test_post_admin_projects(self) -> None:
        """Test case for post_admin_projects

        """
        pass

    def test_post_admin_projects_iri_projectiri_restrictedviewsettings(self) -> None:
        """Test case for post_admin_projects_iri_projectiri_restrictedviewsettings

        """
        pass

    def test_post_admin_projects_shortcode_projectshortcode_export(self) -> None:
        """Test case for post_admin_projects_shortcode_projectshortcode_export

        """
        pass

    def test_post_admin_projects_shortcode_projectshortcode_export_await(self) -> None:
        """Test case for post_admin_projects_shortcode_projectshortcode_export_await

        """
        pass

    def test_post_admin_projects_shortcode_projectshortcode_import(self) -> None:
        """Test case for post_admin_projects_shortcode_projectshortcode_import

        """
        pass

    def test_post_admin_projects_shortcode_projectshortcode_restrictedviewsettings(self) -> None:
        """Test case for post_admin_projects_shortcode_projectshortcode_restrictedviewsettings

        """
        pass

    def test_put_admin_projects_iri_projectiri(self) -> None:
        """Test case for put_admin_projects_iri_projectiri

        """
        pass


if __name__ == '__main__':
    unittest.main()
