# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.child_node_delete_response_adm import ChildNodeDeleteResponseADM

class TestChildNodeDeleteResponseADM(unittest.TestCase):
    """ChildNodeDeleteResponseADM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChildNodeDeleteResponseADM:
        """Test ChildNodeDeleteResponseADM
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChildNodeDeleteResponseADM`
        """
        model = ChildNodeDeleteResponseADM()
        if include_optional:
            return ChildNodeDeleteResponseADM(
                node = None
            )
        else:
            return ChildNodeDeleteResponseADM(
                node = None,
        )
        """

    def testChildNodeDeleteResponseADM(self):
        """Test ChildNodeDeleteResponseADM"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
