# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.license_dto import LicenseDto

class TestLicenseDto(unittest.TestCase):
    """LicenseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LicenseDto:
        """Test LicenseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LicenseDto`
        """
        model = LicenseDto()
        if include_optional:
            return LicenseDto(
                id = '',
                uri = '',
                label_en = ''
            )
        else:
            return LicenseDto(
                id = '',
                uri = '',
                label_en = '',
        )
        """

    def testLicenseDto(self):
        """Test LicenseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
