# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_v2_authentication400_response import GetV2Authentication400Response

class TestGetV2Authentication400Response(unittest.TestCase):
    """GetV2Authentication400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetV2Authentication400Response:
        """Test GetV2Authentication400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetV2Authentication400Response`
        """
        model = GetV2Authentication400Response()
        if include_optional:
            return GetV2Authentication400Response(
                message = '',
                msg = ''
            )
        else:
            return GetV2Authentication400Response(
                message = '',
                msg = '',
        )
        """

    def testGetV2Authentication400Response(self):
        """Test GetV2Authentication400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
