# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_maintenance_api import AdminMaintenanceApi


class TestAdminMaintenanceApi(unittest.TestCase):
    """AdminMaintenanceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminMaintenanceApi()

    def tearDown(self) -> None:
        pass

    def test_post_admin_maintenance_action_name(self) -> None:
        """Test case for post_admin_maintenance_action_name

        """
        pass


if __name__ == '__main__':
    unittest.main()
