# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_users_api import AdminUsersApi


class TestAdminUsersApi(unittest.TestCase):
    """AdminUsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminUsersApi()

    def tearDown(self) -> None:
        pass

    def test_delete_admin_users_iri_useriri(self) -> None:
        """Test case for delete_admin_users_iri_useriri

        """
        pass

    def test_delete_admin_users_iri_useriri_group_memberships_groupiri(self) -> None:
        """Test case for delete_admin_users_iri_useriri_group_memberships_groupiri

        """
        pass

    def test_delete_admin_users_iri_useriri_project_admin_memberships_projectiri(self) -> None:
        """Test case for delete_admin_users_iri_useriri_project_admin_memberships_projectiri

        """
        pass

    def test_delete_admin_users_iri_useriri_project_memberships_projectiri(self) -> None:
        """Test case for delete_admin_users_iri_useriri_project_memberships_projectiri

        """
        pass

    def test_get_admin_users(self) -> None:
        """Test case for get_admin_users

        """
        pass

    def test_get_admin_users_email_email(self) -> None:
        """Test case for get_admin_users_email_email

        """
        pass

    def test_get_admin_users_iri_useriri(self) -> None:
        """Test case for get_admin_users_iri_useriri

        """
        pass

    def test_get_admin_users_iri_useriri_group_memberships(self) -> None:
        """Test case for get_admin_users_iri_useriri_group_memberships

        """
        pass

    def test_get_admin_users_iri_useriri_project_admin_memberships(self) -> None:
        """Test case for get_admin_users_iri_useriri_project_admin_memberships

        """
        pass

    def test_get_admin_users_iri_useriri_project_memberships(self) -> None:
        """Test case for get_admin_users_iri_useriri_project_memberships

        """
        pass

    def test_get_admin_users_username_username(self) -> None:
        """Test case for get_admin_users_username_username

        """
        pass

    def test_post_admin_users(self) -> None:
        """Test case for post_admin_users

        """
        pass

    def test_post_admin_users_iri_useriri_group_memberships_groupiri(self) -> None:
        """Test case for post_admin_users_iri_useriri_group_memberships_groupiri

        """
        pass

    def test_post_admin_users_iri_useriri_project_admin_memberships_projectiri(self) -> None:
        """Test case for post_admin_users_iri_useriri_project_admin_memberships_projectiri

        """
        pass

    def test_post_admin_users_iri_useriri_project_memberships_projectiri(self) -> None:
        """Test case for post_admin_users_iri_useriri_project_memberships_projectiri

        """
        pass

    def test_put_admin_users_iri_useriri_basicuserinformation(self) -> None:
        """Test case for put_admin_users_iri_useriri_basicuserinformation

        """
        pass

    def test_put_admin_users_iri_useriri_password(self) -> None:
        """Test case for put_admin_users_iri_useriri_password

        """
        pass

    def test_put_admin_users_iri_useriri_status(self) -> None:
        """Test case for put_admin_users_iri_useriri_status

        """
        pass

    def test_put_admin_users_iri_useriri_systemadmin(self) -> None:
        """Test case for put_admin_users_iri_useriri_systemadmin

        """
        pass


if __name__ == '__main__':
    unittest.main()
