# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.comments import Comments

class TestComments(unittest.TestCase):
    """Comments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Comments:
        """Test Comments
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Comments`
        """
        model = Comments()
        if include_optional:
            return Comments(
                value = [
                    openapi_client.models.string_literal_v2.StringLiteralV2(
                        value = '', 
                        language = '', )
                    ]
            )
        else:
            return Comments(
        )
        """

    def testComments(self):
        """Test Comments"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
