# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.iri_password import IriPassword

class TestIriPassword(unittest.TestCase):
    """IriPassword unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IriPassword:
        """Test IriPassword
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IriPassword`
        """
        model = IriPassword()
        if include_optional:
            return IriPassword(
                iri = openapi_client.models.user_iri.UserIri(
                    value = '', ),
                password = ''
            )
        else:
            return IriPassword(
                iri = openapi_client.models.user_iri.UserIri(
                    value = '', ),
                password = '',
        )
        """

    def testIriPassword(self):
        """Test IriPassword"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
