# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.permissions_data_adm import PermissionsDataADM

class TestPermissionsDataADM(unittest.TestCase):
    """PermissionsDataADM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PermissionsDataADM:
        """Test PermissionsDataADM
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PermissionsDataADM`
        """
        model = PermissionsDataADM()
        if include_optional:
            return PermissionsDataADM(
                groups_per_project = {
                    'key' : [
                        ''
                        ]
                    },
                administrative_permissions_per_project = {
                    'key' : [
                        openapi_client.models.permission_adm.PermissionADM(
                            name = '', 
                            additional_information = '', 
                            permission_code = 56, )
                        ]
                    }
            )
        else:
            return PermissionsDataADM(
                groups_per_project = {
                    'key' : [
                        ''
                        ]
                    },
                administrative_permissions_per_project = {
                    'key' : [
                        openapi_client.models.permission_adm.PermissionADM(
                            name = '', 
                            additional_information = '', 
                            permission_code = 56, )
                        ]
                    },
        )
        """

    def testPermissionsDataADM(self):
        """Test PermissionsDataADM"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
