# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.v2_lists_api import V2ListsApi


class TestV2ListsApi(unittest.TestCase):
    """V2ListsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = V2ListsApi()

    def tearDown(self) -> None:
        pass

    def test_get_v2_lists_listiri(self) -> None:
        """Test case for get_v2_lists_listiri

        """
        pass

    def test_get_v2_node_listiri(self) -> None:
        """Test case for get_v2_node_listiri

        """
        pass


if __name__ == '__main__':
    unittest.main()
