# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.v2_values_api import V2ValuesApi


class TestV2ValuesApi(unittest.TestCase):
    """V2ValuesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = V2ValuesApi()

    def tearDown(self) -> None:
        pass

    def test_get_v2_values_resourceiri_valueuuid(self) -> None:
        """Test case for get_v2_values_resourceiri_valueuuid

        """
        pass

    def test_post_v2_values(self) -> None:
        """Test case for post_v2_values

        """
        pass

    def test_post_v2_values_delete(self) -> None:
        """Test case for post_v2_values_delete

        """
        pass

    def test_put_v2_values(self) -> None:
        """Test case for put_v2_values

        """
        pass


if __name__ == '__main__':
    unittest.main()
