# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.v2_resources_api import V2ResourcesApi


class TestV2ResourcesApi(unittest.TestCase):
    """V2ResourcesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = V2ResourcesApi()

    def tearDown(self) -> None:
        pass

    def test_get_v2_graph_resourceiri(self) -> None:
        """Test case for get_v2_graph_resourceiri

        """
        pass

    def test_get_v2_resources(self) -> None:
        """Test case for get_v2_resources

        """
        pass

    def test_get_v2_resources_history_resourceiri(self) -> None:
        """Test case for get_v2_resources_history_resourceiri

        """
        pass

    def test_get_v2_resources_iiifmanifest_resourceiri(self) -> None:
        """Test case for get_v2_resources_iiifmanifest_resourceiri

        """
        pass

    def test_get_v2_resources_info(self) -> None:
        """Test case for get_v2_resources_info

        """
        pass

    def test_get_v2_resources_projecthistoryevents_projectiri(self) -> None:
        """Test case for get_v2_resources_projecthistoryevents_projectiri

        """
        pass

    def test_get_v2_resources_resourcehistoryevents_resourceiri(self) -> None:
        """Test case for get_v2_resources_resourcehistoryevents_resourceiri

        """
        pass

    def test_get_v2_resourcespreview(self) -> None:
        """Test case for get_v2_resourcespreview

        """
        pass

    def test_get_v2_tei_resourceiri(self) -> None:
        """Test case for get_v2_tei_resourceiri

        """
        pass

    def test_post_v2_resources(self) -> None:
        """Test case for post_v2_resources

        """
        pass

    def test_post_v2_resources_delete(self) -> None:
        """Test case for post_v2_resources_delete

        """
        pass

    def test_post_v2_resources_erase(self) -> None:
        """Test case for post_v2_resources_erase

        """
        pass

    def test_put_v2_resources(self) -> None:
        """Test case for put_v2_resources

        """
        pass


if __name__ == '__main__':
    unittest.main()
