# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.v2_ontologies_api import V2OntologiesApi


class TestV2OntologiesApi(unittest.TestCase):
    """V2OntologiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = V2OntologiesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_v2_ontologies_classes_comment_resourceclassiri(self) -> None:
        """Test case for delete_v2_ontologies_classes_comment_resourceclassiri

        """
        pass

    def test_delete_v2_ontologies_classes_resourceclassiri(self) -> None:
        """Test case for delete_v2_ontologies_classes_resourceclassiri

        """
        pass

    def test_delete_v2_ontologies_comment_ontologyiri(self) -> None:
        """Test case for delete_v2_ontologies_comment_ontologyiri

        """
        pass

    def test_delete_v2_ontologies_ontologyiri(self) -> None:
        """Test case for delete_v2_ontologies_ontologyiri

        """
        pass

    def test_delete_v2_ontologies_properties_comment_propertyiri(self) -> None:
        """Test case for delete_v2_ontologies_properties_comment_propertyiri

        """
        pass

    def test_delete_v2_ontologies_properties_propertyiri(self) -> None:
        """Test case for delete_v2_ontologies_properties_propertyiri

        """
        pass

    def test_get_ontology(self) -> None:
        """Test case for get_ontology

        """
        pass

    def test_get_v2_ontologies_allentities_ontologyiri(self) -> None:
        """Test case for get_v2_ontologies_allentities_ontologyiri

        """
        pass

    def test_get_v2_ontologies_candeleteclass_resourceclassiri(self) -> None:
        """Test case for get_v2_ontologies_candeleteclass_resourceclassiri

        """
        pass

    def test_get_v2_ontologies_candeleteontology_ontologyiri(self) -> None:
        """Test case for get_v2_ontologies_candeleteontology_ontologyiri

        """
        pass

    def test_get_v2_ontologies_canreplacecardinalities_resourceclassiri(self) -> None:
        """Test case for get_v2_ontologies_canreplacecardinalities_resourceclassiri

        """
        pass

    def test_get_v2_ontologies_classes(self) -> None:
        """Test case for get_v2_ontologies_classes

        """
        pass

    def test_get_v2_ontologies_metadata(self) -> None:
        """Test case for get_v2_ontologies_metadata

        """
        pass

    def test_get_v2_ontologies_properties(self) -> None:
        """Test case for get_v2_ontologies_properties

        """
        pass

    def test_patch_v2_ontologies_cardinalities(self) -> None:
        """Test case for patch_v2_ontologies_cardinalities

        """
        pass

    def test_post_v2_ontologies(self) -> None:
        """Test case for post_v2_ontologies

        """
        pass

    def test_post_v2_ontologies_candeletecardinalities(self) -> None:
        """Test case for post_v2_ontologies_candeletecardinalities

        """
        pass

    def test_post_v2_ontologies_cardinalities(self) -> None:
        """Test case for post_v2_ontologies_cardinalities

        """
        pass

    def test_post_v2_ontologies_classes(self) -> None:
        """Test case for post_v2_ontologies_classes

        """
        pass

    def test_post_v2_ontologies_properties(self) -> None:
        """Test case for post_v2_ontologies_properties

        """
        pass

    def test_put_v2_ontologies_cardinalities(self) -> None:
        """Test case for put_v2_ontologies_cardinalities

        """
        pass

    def test_put_v2_ontologies_classes(self) -> None:
        """Test case for put_v2_ontologies_classes

        """
        pass

    def test_put_v2_ontologies_guiorder(self) -> None:
        """Test case for put_v2_ontologies_guiorder

        """
        pass

    def test_put_v2_ontologies_metadata(self) -> None:
        """Test case for put_v2_ontologies_metadata

        """
        pass

    def test_put_v2_ontologies_properties(self) -> None:
        """Test case for put_v2_ontologies_properties

        """
        pass

    def test_put_v2_ontologies_properties_guielement(self) -> None:
        """Test case for put_v2_ontologies_properties_guielement

        """
        pass


if __name__ == '__main__':
    unittest.main()
