# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_child_node_info_adm import ListChildNodeInfoADM

class TestListChildNodeInfoADM(unittest.TestCase):
    """ListChildNodeInfoADM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListChildNodeInfoADM:
        """Test ListChildNodeInfoADM
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListChildNodeInfoADM`
        """
        model = ListChildNodeInfoADM()
        if include_optional:
            return ListChildNodeInfoADM(
                id = '',
                name = '',
                labels = openapi_client.models.string_literal_sequence_v2.StringLiteralSequenceV2(
                    string_literals = [
                        openapi_client.models.string_literal_v2.StringLiteralV2(
                            value = '', 
                            language = '', )
                        ], ),
                comments = openapi_client.models.string_literal_sequence_v2.StringLiteralSequenceV2(
                    string_literals = [
                        openapi_client.models.string_literal_v2.StringLiteralV2(
                            value = '', 
                            language = '', )
                        ], ),
                position = 56,
                has_root_node = ''
            )
        else:
            return ListChildNodeInfoADM(
                id = '',
                labels = openapi_client.models.string_literal_sequence_v2.StringLiteralSequenceV2(
                    string_literals = [
                        openapi_client.models.string_literal_v2.StringLiteralV2(
                            value = '', 
                            language = '', )
                        ], ),
                comments = openapi_client.models.string_literal_sequence_v2.StringLiteralSequenceV2(
                    string_literals = [
                        openapi_client.models.string_literal_v2.StringLiteralV2(
                            value = '', 
                            language = '', )
                        ], ),
                position = 56,
                has_root_node = '',
        )
        """

    def testListChildNodeInfoADM(self):
        """Test ListChildNodeInfoADM"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
