# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.administrative_permissions_for_project_get_response_adm import AdministrativePermissionsForProjectGetResponseADM

class TestAdministrativePermissionsForProjectGetResponseADM(unittest.TestCase):
    """AdministrativePermissionsForProjectGetResponseADM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdministrativePermissionsForProjectGetResponseADM:
        """Test AdministrativePermissionsForProjectGetResponseADM
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdministrativePermissionsForProjectGetResponseADM`
        """
        model = AdministrativePermissionsForProjectGetResponseADM()
        if include_optional:
            return AdministrativePermissionsForProjectGetResponseADM(
                administrative_permissions = [
                    openapi_client.models.administrative_permission_adm.AdministrativePermissionADM(
                        iri = '', 
                        for_project = '', 
                        for_group = '', 
                        has_permissions = [
                            openapi_client.models.permission_adm.PermissionADM(
                                name = '', 
                                additional_information = '', 
                                permission_code = 56, )
                            ], )
                    ]
            )
        else:
            return AdministrativePermissionsForProjectGetResponseADM(
        )
        """

    def testAdministrativePermissionsForProjectGetResponseADM(self):
        """Test AdministrativePermissionsForProjectGetResponseADM"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
