# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.v2_authentication_api import V2AuthenticationApi


class TestV2AuthenticationApi(unittest.TestCase):
    """V2AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = V2AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_delete_v2_authentication(self) -> None:
        """Test case for delete_v2_authentication

        """
        pass

    def test_get_v2_authentication(self) -> None:
        """Test case for get_v2_authentication

        """
        pass

    def test_get_v2_login(self) -> None:
        """Test case for get_v2_login

        """
        pass

    def test_post_v2_authentication(self) -> None:
        """Test case for post_v2_authentication

        """
        pass

    def test_post_v2_login(self) -> None:
        """Test case for post_v2_login

        """
        pass


if __name__ == '__main__':
    unittest.main()
