# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.login_payload import LoginPayload

class TestLoginPayload(unittest.TestCase):
    """LoginPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoginPayload:
        """Test LoginPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoginPayload`
        """
        model = LoginPayload()
        if include_optional:
            return LoginPayload(
                email = openapi_client.models.email.Email(
                    value = '', ),
                password = '',
                iri = openapi_client.models.user_iri.UserIri(
                    value = '', ),
                username = openapi_client.models.username.Username(
                    value = '', )
            )
        else:
            return LoginPayload(
                email = openapi_client.models.email.Email(
                    value = '', ),
                password = '',
                iri = openapi_client.models.user_iri.UserIri(
                    value = '', ),
                username = openapi_client.models.username.Username(
                    value = '', ),
        )
        """

    def testLoginPayload(self):
        """Test LoginPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
