# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.change_permission_resource_class_api_request_adm import ChangePermissionResourceClassApiRequestADM

class TestChangePermissionResourceClassApiRequestADM(unittest.TestCase):
    """ChangePermissionResourceClassApiRequestADM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangePermissionResourceClassApiRequestADM:
        """Test ChangePermissionResourceClassApiRequestADM
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangePermissionResourceClassApiRequestADM`
        """
        model = ChangePermissionResourceClassApiRequestADM()
        if include_optional:
            return ChangePermissionResourceClassApiRequestADM(
                for_resource_class = ''
            )
        else:
            return ChangePermissionResourceClassApiRequestADM(
                for_resource_class = '',
        )
        """

    def testChangePermissionResourceClassApiRequestADM(self):
        """Test ChangePermissionResourceClassApiRequestADM"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
