# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.paged_response_license_dto import PagedResponseLicenseDto

class TestPagedResponseLicenseDto(unittest.TestCase):
    """PagedResponseLicenseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PagedResponseLicenseDto:
        """Test PagedResponseLicenseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PagedResponseLicenseDto`
        """
        model = PagedResponseLicenseDto()
        if include_optional:
            return PagedResponseLicenseDto(
                data = [
                    openapi_client.models.license_dto.LicenseDto(
                        id = '', 
                        uri = '', 
                        label_en = '', )
                    ],
                pagination = openapi_client.models.pagination.Pagination(
                    page_size = 56, 
                    total_items = 56, 
                    total_pages = 56, 
                    current_page = 56, )
            )
        else:
            return PagedResponseLicenseDto(
                data = [
                    openapi_client.models.license_dto.LicenseDto(
                        id = '', 
                        uri = '', 
                        label_en = '', )
                    ],
                pagination = openapi_client.models.pagination.Pagination(
                    page_size = 56, 
                    total_items = 56, 
                    total_pages = 56, 
                    current_page = 56, ),
        )
        """

    def testPagedResponseLicenseDto(self):
        """Test PagedResponseLicenseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
