# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_change_name_request import ListChangeNameRequest

class TestListChangeNameRequest(unittest.TestCase):
    """ListChangeNameRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListChangeNameRequest:
        """Test ListChangeNameRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListChangeNameRequest`
        """
        model = ListChangeNameRequest()
        if include_optional:
            return ListChangeNameRequest(
                name = openapi_client.models.list_name.ListName(
                    value = '', )
            )
        else:
            return ListChangeNameRequest(
                name = openapi_client.models.list_name.ListName(
                    value = '', ),
        )
        """

    def testListChangeNameRequest(self):
        """Test ListChangeNameRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
