# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.default_object_access_permission_get_response_adm import DefaultObjectAccessPermissionGetResponseADM

class TestDefaultObjectAccessPermissionGetResponseADM(unittest.TestCase):
    """DefaultObjectAccessPermissionGetResponseADM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultObjectAccessPermissionGetResponseADM:
        """Test DefaultObjectAccessPermissionGetResponseADM
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultObjectAccessPermissionGetResponseADM`
        """
        model = DefaultObjectAccessPermissionGetResponseADM()
        if include_optional:
            return DefaultObjectAccessPermissionGetResponseADM(
                default_object_access_permission = openapi_client.models.default_object_access_permission_adm.DefaultObjectAccessPermissionADM(
                    iri = '', 
                    for_project = '', 
                    for_group = '', 
                    for_resource_class = '', 
                    for_property = '', 
                    has_permissions = [
                        openapi_client.models.permission_adm.PermissionADM(
                            name = '', 
                            additional_information = '', 
                            permission_code = 56, )
                        ], )
            )
        else:
            return DefaultObjectAccessPermissionGetResponseADM(
                default_object_access_permission = openapi_client.models.default_object_access_permission_adm.DefaultObjectAccessPermissionADM(
                    iri = '', 
                    for_project = '', 
                    for_group = '', 
                    for_resource_class = '', 
                    for_property = '', 
                    has_permissions = [
                        openapi_client.models.permission_adm.PermissionADM(
                            name = '', 
                            additional_information = '', 
                            permission_code = 56, )
                        ], ),
        )
        """

    def testDefaultObjectAccessPermissionGetResponseADM(self):
        """Test DefaultObjectAccessPermissionGetResponseADM"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
