# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.shacl_api import ShaclApi


class TestShaclApi(unittest.TestCase):
    """ShaclApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ShaclApi()

    def tearDown(self) -> None:
        pass

    def test_post_shacl_validate(self) -> None:
        """Test case for post_shacl_validate

        """
        pass


if __name__ == '__main__':
    unittest.main()
