# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.project_create_request import ProjectCreateRequest

class TestProjectCreateRequest(unittest.TestCase):
    """ProjectCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectCreateRequest:
        """Test ProjectCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectCreateRequest`
        """
        model = ProjectCreateRequest()
        if include_optional:
            return ProjectCreateRequest(
                id = openapi_client.models.project_iri.ProjectIri(
                    value = '', ),
                shortname = openapi_client.models.shortname.Shortname(
                    value = '', ),
                shortcode = openapi_client.models.shortcode.Shortcode(
                    value = '', ),
                longname = openapi_client.models.longname.Longname(
                    value = '', ),
                description = [
                    openapi_client.models.description.Description(
                        value = openapi_client.models.string_literal_v2.StringLiteralV2(
                            value = '', 
                            language = '', ), )
                    ],
                keywords = [
                    openapi_client.models.keyword.Keyword(
                        value = '', )
                    ],
                logo = openapi_client.models.logo.Logo(
                    value = '', ),
                status = None,
                selfjoin = None
            )
        else:
            return ProjectCreateRequest(
                shortname = openapi_client.models.shortname.Shortname(
                    value = '', ),
                shortcode = openapi_client.models.shortcode.Shortcode(
                    value = '', ),
                status = None,
                selfjoin = None,
        )
        """

    def testProjectCreateRequest(self):
        """Test ProjectCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
