# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_change_position_request import ListChangePositionRequest

class TestListChangePositionRequest(unittest.TestCase):
    """ListChangePositionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListChangePositionRequest:
        """Test ListChangePositionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListChangePositionRequest`
        """
        model = ListChangePositionRequest()
        if include_optional:
            return ListChangePositionRequest(
                position = openapi_client.models.position.Position(
                    value = 56, ),
                parent_node_iri = openapi_client.models.list_iri.ListIri(
                    value = '', )
            )
        else:
            return ListChangePositionRequest(
                position = openapi_client.models.position.Position(
                    value = 56, ),
                parent_node_iri = openapi_client.models.list_iri.ListIri(
                    value = '', ),
        )
        """

    def testListChangePositionRequest(self):
        """Test ListChangePositionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
