# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_project_admin_memberships_get_response_adm import UserProjectAdminMembershipsGetResponseADM

class TestUserProjectAdminMembershipsGetResponseADM(unittest.TestCase):
    """UserProjectAdminMembershipsGetResponseADM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserProjectAdminMembershipsGetResponseADM:
        """Test UserProjectAdminMembershipsGetResponseADM
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserProjectAdminMembershipsGetResponseADM`
        """
        model = UserProjectAdminMembershipsGetResponseADM()
        if include_optional:
            return UserProjectAdminMembershipsGetResponseADM(
                projects = [
                    openapi_client.models.project.Project(
                        id = openapi_client.models.project_iri.ProjectIri(
                            value = '', ), 
                        shortname = openapi_client.models.shortname.Shortname(
                            value = '', ), 
                        shortcode = openapi_client.models.shortcode.Shortcode(
                            value = '', ), 
                        longname = openapi_client.models.longname.Longname(
                            value = '', ), 
                        description = [
                            openapi_client.models.string_literal_v2.StringLiteralV2(
                                value = '', 
                                language = '', )
                            ], 
                        keywords = [
                            ''
                            ], 
                        logo = openapi_client.models.logo.Logo(
                            value = '', ), 
                        ontologies = [
                            ''
                            ], 
                        status = null, 
                        selfjoin = null, )
                    ]
            )
        else:
            return UserProjectAdminMembershipsGetResponseADM(
        )
        """

    def testUserProjectAdminMembershipsGetResponseADM(self):
        """Test UserProjectAdminMembershipsGetResponseADM"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
