---

name: Setup - Install poetry, python, and dependencies
runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry self add poetry-exec-plugin
      shell: bash
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        # attempt to restore dependencies from cache (if successful, the following `poetry install` will be a no-op)
        cache: poetry
    - name: Install Python dependencies
      run: poetry install
      shell: bash
