---

name: Setup - Install uv, just, python, and dependencies
description: This action contains some setup steps that are common to several workflows
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
    - name: Install just
      uses: taiki-e/install-action@just
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
        # attempt to restore dependencies from cache (if successful, the following `poetry install` will be a no-op)
        cache: poetry
    - name: Install Python dependencies
      run: uv sync --all-extras --dev
      shell: bash
