---

name: Setup - Install uv, just, and dependencies
description: This action contains some setup steps that are common to several workflows
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
    - name: Install just
      uses: taiki-e/install-action@just
    - name: Install Python dependencies (uv will install python automatically, if no appropriate version is installed)
      run: uv sync --all-extras --dev
      shell: bash
