# Configuration of https://pre-commit.com/

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python supported by your project here,
        # or alternatively use pre-commit's default_language_version,
        # see https://pre-commit.com/#top_level-default_language_version
        language_version: python3.11

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: fix-byte-order-marker
      - id: detect-private-key
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
    - id: markdownlint
      args: [--config, .markdownlint.yml, --ignore, CHANGELOG.md]

  - repo: https://github.com/PyCQA/isort 
    rev: 5.11.5
    hooks:
    - id: isort
