# Configuration of https://pre-commit.com/

repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [
          --ignore=A002,  # builtin-argument-shadowing
          --ignore=D101, # missing-module-docstring
          --ignore=D102,  # undocumented-public-class
          --ignore=F841,  # error suppression
          --ignore=FIX002,  # line-contains-to do
          --ignore=PLR0913,  # too-many-arguments
          --ignore=PLR2004,  # magic-value-comparison
        ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: fix-byte-order-marker
      - id: detect-private-key
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
    - id: markdownlint
      args: [--config, .markdownlint.yml, --ignore, CHANGELOG.md]
