version: '3.7'

services:

  app:
    image: daschswiss/dsp-app:v10.11.0  # after every deployment (fortnightly), check latest tag at https://hub.docker.com/r/daschswiss/dsp-app/tags
    ports:
      - "4200:4200"
    networks:
      - knora-net

  db:
    image: daschswiss/apache-jena-fuseki:2.0.8  # after every deployment (fortnightly), check latest tag at https://hub.docker.com/r/daschswiss/apache-jena-fuseki/tags
    ports:
      - "3030:3030"
    networks:
      - knora-net
    environment:
      - TZ=Europe/Zurich
      - ADMIN_PASSWORD=test
      - JVM_ARGS=-Xmx3G

  sipi:
    image: daschswiss/knora-sipi:24.0.8  # after every deployment (fortnightly), check latest tag at https://hub.docker.com/r/daschswiss/knora-sipi/tags
    ports:
      - "1024:1024"
    volumes:
      - .:/docker
    networks:
      - knora-net
    environment:
      - TZ=Europe/Zurich
      - SIPI_EXTERNAL_PROTOCOL=http
      - SIPI_EXTERNAL_HOSTNAME=0.0.0.0
      - SIPI_EXTERNAL_PORT=1024
      - SIPI_WEBAPI_HOSTNAME=api
      - SIPI_WEBAPI_PORT=3333
      - KNORA_WEBAPI_KNORA_API_EXTERNAL_HOST=0.0.0.0
      - KNORA_WEBAPI_KNORA_API_EXTERNAL_PORT=3333
    command: --config=/docker/sipi.docker-config.lua

  api:
    image: daschswiss/knora-api:24.0.8  # after every deployment (fortnightly), check latest tag at https://hub.docker.com/r/daschswiss/knora-api/tags
    depends_on:
      - sipi
      - db
    ports:
      - "3333:3333"
    networks:
      - knora-net
    environment:
      - TZ=Europe/Zurich
      - KNORA_AKKA_LOGLEVEL=DEBUG
      - KNORA_AKKA_STDOUT_LOGLEVEL=DEBUG
      - KNORA_WEBAPI_TRIPLESTORE_HOST=db
      - KNORA_WEBAPI_TRIPLESTORE_DBTYPE=fuseki
      - KNORA_WEBAPI_SIPI_INTERNAL_HOST=sipi
      - KNORA_WEBAPI_TRIPLESTORE_FUSEKI_REPOSITORY_NAME=knora-test
      - KNORA_WEBAPI_TRIPLESTORE_FUSEKI_USERNAME=admin
      - KNORA_WEBAPI_TRIPLESTORE_FUSEKI_PASSWORD=test
      - KNORA_WEBAPI_CACHE_SERVICE_ENABLED=true
      - KNORA_WEBAPI_CACHE_SERVICE_REDIS_HOST=redis
      - KNORA_WEBAPI_CACHE_SERVICE_REDIS_PORT=6379
      - KNORA_WEBAPI_ALLOW_RELOAD_OVER_HTTP=true
      - KNORA_WEBAPI_KNORA_API_EXTERNAL_HOST=0.0.0.0
      - KNORA_WEBAPI_KNORA_API_EXTERNAL_PORT=3333

networks:
  knora-net:
    name: knora-net
