# coding: utf-8

"""
    dsp-ingest

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.19.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.bulk_ingest_api import BulkIngestApi


class TestBulkIngestApi(unittest.TestCase):
    """BulkIngestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BulkIngestApi()

    def tearDown(self) -> None:
        pass

    def test_get_projects_shortcode_bulk_ingest_mapping_csv(self) -> None:
        """Test case for get_projects_shortcode_bulk_ingest_mapping_csv

        """
        pass

    def test_post_projects_shortcode_bulk_ingest(self) -> None:
        """Test case for post_projects_shortcode_bulk_ingest

        """
        pass

    def test_post_projects_shortcode_bulk_ingest_finalize(self) -> None:
        """Test case for post_projects_shortcode_bulk_ingest_finalize

        """
        pass

    def test_post_projects_shortcode_bulk_ingest_ingest_file(self) -> None:
        """Test case for post_projects_shortcode_bulk_ingest_ingest_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
