# coding: utf-8

"""
    dsp-ingest

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.19.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_projects_shortcode_erase(self) -> None:
        """Test case for delete_projects_shortcode_erase

        """
        pass

    def test_get_projects(self) -> None:
        """Test case for get_projects

        """
        pass

    def test_get_projects_shortcode(self) -> None:
        """Test case for get_projects_shortcode

        """
        pass

    def test_get_projects_shortcode_checksumreport(self) -> None:
        """Test case for get_projects_shortcode_checksumreport

        """
        pass


if __name__ == '__main__':
    unittest.main()
