# coding: utf-8

"""
    dsp-ingest

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.19.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.monitoring_api import MonitoringApi


class TestMonitoringApi(unittest.TestCase):
    """MonitoringApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MonitoringApi()

    def tearDown(self) -> None:
        pass

    def test_get_health(self) -> None:
        """Test case for get_health

        """
        pass

    def test_get_info(self) -> None:
        """Test case for get_info

        """
        pass

    def test_get_metrics(self) -> None:
        """Test case for get_metrics

        """
        pass


if __name__ == '__main__':
    unittest.main()
