# coding: utf-8

"""
    dsp-ingest

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.19.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.action_name import ActionName

class TestActionName(unittest.TestCase):
    """ActionName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActionName(self):
        """Test ActionName"""
        # inst = ActionName()

if __name__ == '__main__':
    unittest.main()
