---

name: Setup - Install uv, python, build & install wheel, install pytest
description: Simulate an end-user installation of DSP-TOOLS. Specifically for the distribution tests.
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
    - name: Install python
      run: uv python install
      shell: bash
    - name: Build wheel
      run: |
        echo ########### STEP: BUILD WHEEL ###########
        uv build .
      shell: bash
    - name: check the wheel for correctness, in dedicated venv
      run: |
        echo ########### STEP: CHECK WHEEL IN DEDICATED VENV ###########
        uvx check-wheel-contents dist/
      shell: bash
    - name: Install wheel globally
      run: |
        echo ########### STEP: INSTALL WHEEL GLOBALLY ###########
        find dist -type f -name "*.whl" -exec uv pip install --system {} \;
      shell: bash
    - name: Install pytest globally
      run: |
        echo ########### STEP: INSTALL PYTEST GLOBALLY ###########
        uv pip install --system pytest pytest-unordered
      shell: bash
