---

name: Setup - Install python & poetry, build & install wheel, install pytest
runs:
  using: "composite"
  steps:
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install poetry
      run: | 
        echo ########### STEP: INSTALL POETRY ###########
        curl -sSL https://install.python-poetry.org | python3 -
      shell: bash
    - name: Build wheel
      run: |
        echo ########### STEP: BUILD WHEEL ###########
        poetry build -vv
      shell: bash
    - name: Install wheel
      run: |
        echo ########### STEP: INSTALL WHEEL ###########
        find dist -type f -name "*.whl" -exec pip3 install {} \;
      shell: bash
    - name: install check-wheel-contents
      run: |
        echo ########### STEP: INSTALL CHECK-WHEEL-CONTENTS ###########
        pip3 install check-wheel-contents
      shell: bash
    - name: check the wheel for correctness
      run: |
        echo ########### STEP: CHECK WHEEL ###########
        check-wheel-contents dist/
      shell: bash
    - name: Install pytest
      run: |
        echo ########### STEP: INSTALL PYTEST ###########
        pip3 install pytest pytest-unordered
      shell: bash
