---

name: Setup - Install python & poetry, build & install wheel, install pytest
runs:
  using: "composite"
  steps:
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
      shell: bash
    - name: Build & install wheel
      run: |
        poetry build
        find dist -type f -name "*.whl" -exec pip3 install {} \;
      shell: bash
    - name: check the wheel for correctness
      run: |
        poetry add --group dev check-wheel-contents
        poetry run check-wheel-contents dist/
      shell: bash
    - name: Install pytest
      run: pip3 install pytest pytest-unordered
      shell: bash
