---

name: Setup - Install uv, build & install wheel
description: Simulate an end-user installation of DSP-TOOLS. Specifically for the distribution tests.
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
    - name: Build wheel
      run: |
        echo ########### STEP: BUILD WHEEL ###########
        uv build . -vv
      shell: bash
    - name: Install wheel globally
      run: |
        echo ########### STEP: INSTALL WHEEL GLOBALLY ###########
        find dist -type f -name "*.whl" -exec uv pip install {} \;
      shell: bash
    - name: check the wheel for correctness, in dedicated venv
      run: |
        echo ########### STEP: CHECK WHEEL IN DEDICATED VENV ###########
        uvx check-wheel-contents dist/
      shell: bash
