---

name: Setup - Install poetry & python, build & install wheel, install pytest
runs:
  using: "composite"
  steps:
    - run: curl -sSL https://install.python-poetry.org | python3 -
      shell: bash
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Build & install wheel
      run: |
        poetry build
        cd dist && ls                    # just for testing, remove that later
        pip3 install dist/*.whl
      shell: bash
    - name: Install pytest
      run: pip3 install pytest pytest-unordered
      shell: bash
