# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.permission_adm import PermissionADM
from typing import Optional, Set
from typing_extensions import Self

class AdministrativePermissionADM(BaseModel):
    """
    AdministrativePermissionADM
    """ # noqa: E501
    iri: StrictStr
    for_project: StrictStr = Field(alias="forProject")
    for_group: StrictStr = Field(alias="forGroup")
    has_permissions: Optional[List[PermissionADM]] = Field(default=None, alias="hasPermissions")
    __properties: ClassVar[List[str]] = ["iri", "forProject", "forGroup", "hasPermissions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdministrativePermissionADM from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in has_permissions (list)
        _items = []
        if self.has_permissions:
            for _item_has_permissions in self.has_permissions:
                if _item_has_permissions:
                    _items.append(_item_has_permissions.to_dict())
            _dict['hasPermissions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdministrativePermissionADM from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "iri": obj.get("iri"),
            "forProject": obj.get("forProject"),
            "forGroup": obj.get("forGroup"),
            "hasPermissions": [PermissionADM.from_dict(_item) for _item in obj["hasPermissions"]] if obj.get("hasPermissions") is not None else None
        })
        return _obj


