# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from openapi_client.models.bad_request_exception import BadRequestException
from openapi_client.models.duplicate_value_exception import DuplicateValueException
from openapi_client.models.gravsearch_exception import GravsearchException
from openapi_client.models.ontology_constraint_exception import OntologyConstraintException
from openapi_client.models.validation_exception import ValidationException
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

GETV2AUTHENTICATION400RESPONSE_ANY_OF_SCHEMAS = ["BadRequestException", "DuplicateValueException", "GravsearchException", "OntologyConstraintException", "ValidationException"]

class GetV2Authentication400Response(BaseModel):
    """
    GetV2Authentication400Response
    """

    # data type: OntologyConstraintException
    anyof_schema_1_validator: Optional[OntologyConstraintException] = None
    # data type: DuplicateValueException
    anyof_schema_2_validator: Optional[DuplicateValueException] = None
    # data type: GravsearchException
    anyof_schema_3_validator: Optional[GravsearchException] = None
    # data type: ValidationException
    anyof_schema_4_validator: Optional[ValidationException] = None
    # data type: BadRequestException
    anyof_schema_5_validator: Optional[BadRequestException] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[BadRequestException, DuplicateValueException, GravsearchException, OntologyConstraintException, ValidationException]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "BadRequestException", "DuplicateValueException", "GravsearchException", "OntologyConstraintException", "ValidationException" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = GetV2Authentication400Response.model_construct()
        error_messages = []
        # validate data type: OntologyConstraintException
        if not isinstance(v, OntologyConstraintException):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OntologyConstraintException`")
        else:
            return v

        # validate data type: DuplicateValueException
        if not isinstance(v, DuplicateValueException):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DuplicateValueException`")
        else:
            return v

        # validate data type: GravsearchException
        if not isinstance(v, GravsearchException):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GravsearchException`")
        else:
            return v

        # validate data type: ValidationException
        if not isinstance(v, ValidationException):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ValidationException`")
        else:
            return v

        # validate data type: BadRequestException
        if not isinstance(v, BadRequestException):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BadRequestException`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in GetV2Authentication400Response with anyOf schemas: BadRequestException, DuplicateValueException, GravsearchException, OntologyConstraintException, ValidationException. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[OntologyConstraintException] = None
        try:
            instance.actual_instance = OntologyConstraintException.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[DuplicateValueException] = None
        try:
            instance.actual_instance = DuplicateValueException.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[GravsearchException] = None
        try:
            instance.actual_instance = GravsearchException.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[ValidationException] = None
        try:
            instance.actual_instance = ValidationException.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[BadRequestException] = None
        try:
            instance.actual_instance = BadRequestException.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into GetV2Authentication400Response with anyOf schemas: BadRequestException, DuplicateValueException, GravsearchException, OntologyConstraintException, ValidationException. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], BadRequestException, DuplicateValueException, GravsearchException, OntologyConstraintException, ValidationException]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


