# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.child_node_delete_response_adm import ChildNodeDeleteResponseADM
from openapi_client.models.list_delete_response_adm import ListDeleteResponseADM
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

LISTITEMDELETERESPONSEADM_ONE_OF_SCHEMAS = ["ChildNodeDeleteResponseADM", "ListDeleteResponseADM"]

class ListItemDeleteResponseADM(BaseModel):
    """
    ListItemDeleteResponseADM
    """
    # data type: ChildNodeDeleteResponseADM
    oneof_schema_1_validator: Optional[ChildNodeDeleteResponseADM] = None
    # data type: ListDeleteResponseADM
    oneof_schema_2_validator: Optional[ListDeleteResponseADM] = None
    actual_instance: Optional[Union[ChildNodeDeleteResponseADM, ListDeleteResponseADM]] = None
    one_of_schemas: Set[str] = { "ChildNodeDeleteResponseADM", "ListDeleteResponseADM" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ListItemDeleteResponseADM.model_construct()
        error_messages = []
        match = 0
        # validate data type: ChildNodeDeleteResponseADM
        if not isinstance(v, ChildNodeDeleteResponseADM):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ChildNodeDeleteResponseADM`")
        else:
            match += 1
        # validate data type: ListDeleteResponseADM
        if not isinstance(v, ListDeleteResponseADM):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ListDeleteResponseADM`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ListItemDeleteResponseADM with oneOf schemas: ChildNodeDeleteResponseADM, ListDeleteResponseADM. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ListItemDeleteResponseADM with oneOf schemas: ChildNodeDeleteResponseADM, ListDeleteResponseADM. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ChildNodeDeleteResponseADM
        try:
            instance.actual_instance = ChildNodeDeleteResponseADM.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ListDeleteResponseADM
        try:
            instance.actual_instance = ListDeleteResponseADM.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ListItemDeleteResponseADM with oneOf schemas: ChildNodeDeleteResponseADM, ListDeleteResponseADM. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ListItemDeleteResponseADM with oneOf schemas: ChildNodeDeleteResponseADM, ListDeleteResponseADM. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ChildNodeDeleteResponseADM, ListDeleteResponseADM]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


