# coding: utf-8

"""
    DSP-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_client.models.permission_adm import PermissionADM
from typing import Optional, Set
from typing_extensions import Self

class PermissionsDataADM(BaseModel):
    """
    PermissionsDataADM
    """ # noqa: E501
    groups_per_project: Dict[str, List[StrictStr]] = Field(alias="groupsPerProject")
    administrative_permissions_per_project: Dict[str, List[PermissionADM]] = Field(alias="administrativePermissionsPerProject")
    __properties: ClassVar[List[str]] = ["groupsPerProject", "administrativePermissionsPerProject"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PermissionsDataADM from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in administrative_permissions_per_project (dict of array)
        _field_dict_of_array = {}
        if self.administrative_permissions_per_project:
            for _key_administrative_permissions_per_project in self.administrative_permissions_per_project:
                if self.administrative_permissions_per_project[_key_administrative_permissions_per_project] is not None:
                    _field_dict_of_array[_key_administrative_permissions_per_project] = [
                        _item.to_dict() for _item in self.administrative_permissions_per_project[_key_administrative_permissions_per_project]
                    ]
            _dict['administrativePermissionsPerProject'] = _field_dict_of_array
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PermissionsDataADM from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "groupsPerProject": obj.get("groupsPerProject"),
            "administrativePermissionsPerProject": dict(
                (_k,
                        [PermissionADM.from_dict(_item) for _item in _v]
                        if _v is not None
                        else None
                )
                for _k, _v in obj.get("administrativePermissionsPerProject", {}).items()
            )
        })
        return _obj


