"""
dsp-ingest

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.19.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from src.dsp_tools.clients.openapi_ingest.openapi_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_projects_shortcode_erase(self) -> None:
        """Test case for delete_projects_shortcode_erase"""

    def test_get_projects(self) -> None:
        """Test case for get_projects"""

    def test_get_projects_shortcode(self) -> None:
        """Test case for get_projects_shortcode"""

    def test_get_projects_shortcode_checksumreport(self) -> None:
        """Test case for get_projects_shortcode_checksumreport"""


if __name__ == "__main__":
    unittest.main()
