"""
dsp-ingest

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.19.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from src.dsp_tools.clients.openapi_ingest.openapi_client.models.unhealthy import Unhealthy


class TestUnhealthy(unittest.TestCase):
    """Unhealthy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Unhealthy:
        """Test Unhealthy
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Unhealthy`
        """
        model = Unhealthy()
        if include_optional:
            return Unhealthy(
                status = None,
                components = {
                    'key' : openapi_client.models.health.Health(
                        status = null, )
                    }
            )
        else:
            return Unhealthy(
                status = None,
        )
        """

    def testUnhealthy(self):
        """Test Unhealthy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
