"""
dsp-ingest

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.19.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from src.dsp_tools.clients.openapi_ingest.openapi_client.api.assets_api import AssetsApi


class TestAssetsApi(unittest.TestCase):
    """AssetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetsApi()

    def tearDown(self) -> None:
        pass

    def test_get_projects_shortcode_assets_assetid(self) -> None:
        """Test case for get_projects_shortcode_assets_assetid"""

    def test_get_projects_shortcode_assets_assetid_original(self) -> None:
        """Test case for get_projects_shortcode_assets_assetid_original"""

    def test_post_projects_shortcode_assets_ingest_filename(self) -> None:
        """Test case for post_projects_shortcode_assets_ingest_filename"""


if __name__ == "__main__":
    unittest.main()
