"""
dsp-ingest

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.19.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from src.dsp_tools.clients.openapi_ingest.openapi_client.api.import_export_api import ImportExportApi


class TestImportExportApi(unittest.TestCase):
    """ImportExportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImportExportApi()

    def tearDown(self) -> None:
        pass

    def test_get_projects_shortcode_import(self) -> None:
        """Test case for get_projects_shortcode_import"""

    def test_post_projects_shortcode_export(self) -> None:
        """Test case for post_projects_shortcode_export"""


if __name__ == "__main__":
    unittest.main()
