"""
dsp-ingest

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.19.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from src.dsp_tools.clients.openapi_ingest.openapi_client.api.monitoring_api import MonitoringApi


class TestMonitoringApi(unittest.TestCase):
    """MonitoringApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MonitoringApi()

    def tearDown(self) -> None:
        pass

    def test_get_health(self) -> None:
        """Test case for get_health"""

    def test_get_info(self) -> None:
        """Test case for get_info"""

    def test_get_metrics(self) -> None:
        """Test case for get_metrics"""


if __name__ == "__main__":
    unittest.main()
