"""
dsp-ingest

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0.19.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from src.dsp_tools.clients.openapi_ingest.openapi_client.models.conflict import Conflict


class TestConflict(unittest.TestCase):
    """Conflict unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Conflict:
        """Test Conflict
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Conflict`
        """
        model = Conflict()
        if include_optional:
            return Conflict(
                reason = ''
            )
        else:
            return Conflict(
                reason = '',
        )
        """

    def testConflict(self):
        """Test Conflict"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
