# coding: utf-8

"""
    dsp-ingest

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.19.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.forbidden import Forbidden

class TestForbidden(unittest.TestCase):
    """Forbidden unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Forbidden:
        """Test Forbidden
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Forbidden`
        """
        model = Forbidden()
        if include_optional:
            return Forbidden(
                reason = ''
            )
        else:
            return Forbidden(
                reason = '',
        )
        """

    def testForbidden(self):
        """Test Forbidden"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
