name: "Preparation"
description: "Preparation steps to run tests"

runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install poetry
      shell: bin/bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry self add poetry-exec-plugin

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        # attempt to restore dependencies from cache (if successful, the following `poetry install` will be a no-op)
        cache: poetry

    - name: Install Python dependencies
      shell: bin/bash
      run: poetry install
