# Bandit is a security linter designed to find common security issues in Python code.

name: Bandit
on:
  schedule:
    - cron: '15 0 * * 1'

jobs:
  bandit:
    permissions:
      contents: read                                    # for actions/checkout to fetch code
      security-events: write                            # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read                                     # only required for a private repository by 
                                                        # github/codeql-action/upload-sarif to get the Action run status


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@main
        with:                                           # optional arguments
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     # needed to get PR information
          level: high
          confidence: medium
          exit_zero: true                               # exit with 0, even with results found
