name: PR-Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  test:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      # check PR title
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '([a-z])+(\(([a-z\-_ ])+\))?!?: [a-z]([a-zA-Z-\.\d \(\)\[\]#_])+$' # Regex the title should match.
          allowed_prefixes: 'fix,refactor,feat,docs,chore,style,test' # title should start with the given prefix
          disallowed_prefixes: 'feature,hotfix' # title should not start with the given prefix
          prefix_case_sensitive: true # title prefix are case insensitive
          min_length: 7 # Min length of the title
          max_length: 120 # Max length of the title
