name: Daily test

on:
  schedule:
    -  cron: '0 7 * * *'

jobs:
    tests:
        name: daily-tests
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout source
                uses: actions/checkout@v2
                with:
                    fetch-depth: 1
            -   name: Set up Python 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            -   name: Install dependencies
                run: |
                    make upgrade-dist-tools
                    make install-requirements
                    make install
            -   name: Run e2e tests
                run: make test-end-to-end
