name: Daily test

on:
    schedule:
        -   cron: '0 7 * * *'

jobs:
    daily-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out repo
                uses: actions/checkout@v3
                with:
                    fetch-depth: 1
            -   name: Set up Python 3.9
                uses: actions/setup-python@v4
                with:
                    python-version: 3.9
            -   name: Install dependencies
                run: |
                    curl -sSL https://install.python-poetry.org | python3 -
                    poetry install
            -   name: Run e2e tests
                run: |
                    poetry run dsp-tools start-stack --no-prune
                    poetry run pytest test/e2e/
