---

name: Publish dev-release to PyPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TWINE_USERNAME: __token__  # If an API token is used as pw, the username must be "__token__"
  TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}

jobs:
  publish-dev-release-to-pypi:
    if: startsWith(github.event.head_commit.message, 'fix') || startsWith(github.event.head_commit.message, 'feat')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - name: Install just
        uses: taiki-e/install-action@just
      - name: bump version in pyproject.toml
        run: just bump-version
      - name: build wheel
        run: uv build .
      - name: publish new version to PyPI
        run: uvx twine upload --repository-url=https://test.pypi.org/legacy/ dist/*
