---

name: Publish dev-release to PyPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # API tokens require username "__token__".
  # Repo names other than pypi.org must be configured with:
  #  % poetry config repositories.testpypi https://test.pypi.org/legacy/
  # and the env vars must be named accordingly:
  #  - POETRY_HTTP_BASIC_<REPO>_USERNAME
  #  - POETRY_PYPI_TOKEN_<REPO>
  POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
  POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_DASCHBOT_TOKEN }}

jobs:
  publish-dev-release-to-pypi:
    if: startsWith(github.event.head_commit.message, 'fix') || startsWith(github.event.head_commit.message, 'feat')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv, just, python, and dependencies
        uses: ./.github/actions/setup
      - name: bump version in pyproject.toml
        run: just bump-version
      - name: build wheel
        run: uv build .
      - name: publish new version to PyPI
        run: poetry publish
