name: Release

on:
  release:
    types: [released]

# set environment variables
env:
  TOKEN: ${{ secrets.GH_TOKEN }}
  TWINE_USERNAME: ${{ secrets.PYPI_USER }}
  TWINE_PASSWORD: ${{ secrets.PYPI_PW }}

jobs:
  release-integration:
    name: Release to PyPI and make Docs
    runs-on: ubuntu-latest
    steps:
      # check out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      # install python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      # install pythonn dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # release new version to PyPI
      - run: |
          make upgrade-dist-tools
          make dist
          make upload
      # release latest docs
      - run: make publish-docs
