name: Release

on:
  release:
    types: [released]

# set environment variables
env:
  TOKEN: ${{ secrets.GH_TOKEN }}
  TWINE_USERNAME: ${{ secrets.PYPI_USER }}
  TWINE_PASSWORD: ${{ secrets.PYPI_PW }}

jobs:
  # release to PyPI
  release-pypi:
    name: Release to PyPI
    runs-on: ubuntu-latest
    steps:
      # check out repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      # install python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # install python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      # release new version to PyPI
      - run: |
          make dist
          make upload

  notification:
    name: Google chat notification about release and published version
    needs: [release-pypi]
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to google chat room "DSP releases"
        uses: lakto/google-chat-action@main
        with:
          url: ${{ secrets.GOOGLE_CHAT_DSP_RELEASES_WEBHOOK_URL }}
