name: test-docs

on: [push]

# set environment variables
env:
  TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release-docs:
    name: Release Docs
    runs-on: ubuntu-latest
    steps:
      # check out repo
      - uses: actions/checkout@v2
      # install python
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}