---

name: Tests

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read

env:
  DSP_TOOLS_TESTING: true

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dsp-tools repo
        uses: actions/checkout@v4
      - name: Install uv, just, and dependencies
        uses: ./.github/actions/setup
      - name: unittests
        run: just unittests --cov=dsp_tools --cov-report xml
      - name: upload coverage report to codecov.io
        uses: codecov/codecov-action@v4
        with:
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dsp-tools repo
        uses: actions/checkout@v4
      - name: Install uv, just, and dependencies
        uses: ./.github/actions/setup
      - name: integration-tests
        run: just integration-tests --cov=dsp_tools --cov-report xml
      - name: upload coverage report to codecov.io
        uses: codecov/codecov-action@v5
        with:
          flags: integration-tests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  benchmarking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dsp-tools repo
        uses: actions/checkout@v4
      - name: Install uv, just, and dependencies
        uses: ./.github/actions/setup
      - name: benchmarking
        run: uv run pytest -s test/benchmarking/

  distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dsp-tools repo
        uses: actions/checkout@v4
      - name: Install python, pytest, uv, build & install wheel
        uses: ./.github/actions/setup-from-wheel
      - name: distribution tests
        run: python -m pytest --noconftest test/distribution/
        # Reason for the --noconftest flag: 
        # test/conftest.py configures logging, but loguru should not be installed for the distribution tests
