---

name: Update coverage report of main branch on codecov.io

on:
  push:
    branches:
      - main

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dsp-tools repo
        uses: actions/checkout@v4
      - name: Install uv, just, and dependencies
        uses: ./.github/actions/setup
      - name: unittests
        run: just unittests --cov=dsp_tools --cov-report xml
      - name: upload coverage report to codecov.io
        uses: codecov/codecov-action@v4
        with:
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dsp-tools repo
        uses: actions/checkout@v4
      - name: Install uv, just, and dependencies
        uses: ./.github/actions/setup
      - name: integration-tests
        run: just integration-tests --cov=dsp_tools --cov-report xml
      - name: upload coverage report to codecov.io
        uses: codecov/codecov-action@v4
        with:
          flags: integration-tests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
